### ISSUE TITLE
Unexpected dependency

### ISSUE THREAD

**Issue by mwalzer** [PaulBrack/Yamato#110] opened 2020-01-24 15:32 UTC
Using a call like `Yamato.Console -i collinsb_I180316_005_SW-A.mzML` I get this error and the core dumped:
```
No usable version of libssl was found
Aborted (core dumped)
```

**Comment by mwalzer** [comment] 2020-01-24 15:34
After installing libssl1.1 the error is just like #81

**Comment by mwalzer** [comment] 2020-01-24 15:34
using `v1.0.0-b`

**Comment by PaulBrack** [comment] 2020-01-24 16:05
Looks like we need OpenSSL install on Linux - not sure why you need it? Looks like we can use v1.0 or v1.1 though:

https://stackoverflow.com/questions/53139591/

With OpenSSL installed and #81 fixed, are we okay to close this @mwalzer ?

**Comment by mwalzer** [comment] 2020-01-24 16:29
I was just wondering, as this error was new from the previous build from dropbox to the one that is in `v1.0.0-b`

**Comment by Ozzard** [comment] 2020-02-04 15:57
@mwalzer, could you check this with the latest container release please?  If that works, I'm going to close this with a reference to .Net Core prerequisites.  If it doesn't, I've got some more fixing to do...

**Comment by mwalzer** [comment] 2020-02-05 09:54
```
root@7ee3f51d70cb:/data# Yamato.Console -i collinsb_I180316_005_SW-A.mzML
2020-02-05 09:53:36.8679|INFO|Yamato.Console.Program|Verbose output selected: enabled logging for all levels
2020-02-05 09:53:36.8899|INFO|Yamato.Console.Program|Loading file: collinsb_I180316_005_SW-A.mzML


Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlParser/MzmlReader.cs:line 514
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlParser/MzmlReader.cs:line 344
   at MzmlParser.MzmlReader.<>c__DisplayClass27_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlParser/MzmlReader.cs:line 254
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at MzmlParser.MzmlReader.ExtractFloatArray(String Base64Array, Boolean IsZlibCompressed, Int32 bits) in /home/runner/work/Yamato/Yamato/MzmlParser/MzmlReader.cs:line 514
   at MzmlParser.MzmlReader.ParseBase64Data(ScanAndTempProperties scan, Run run, Boolean extractBasePeaks, Boolean threading, Boolean irt) in /home/runner/work/Yamato/Yamato/MzmlParser/MzmlReader.cs:line 344
   at MzmlParser.MzmlReader.<>c__DisplayClass27_0.<ReadSpectrum>b__1(Object state) in /home/runner/work/Yamato/Yamato/MzmlParser/MzmlReader.cs:line 254
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

**Comment by PaulBrack** [comment] 2020-03-03 13:11
Resolved, this is now a duplicate of 81 (closed): https://github.com/PaulBrack/Yamato/issues/81

**Closed by PaulBrack** 2020-03-03 13:11 UTC
